"""add_extra_permissions_to_user

Revision ID: 7347b087d4d4
Revises: d35c5432f8c1
Create Date: 2026-07-16 17:58:43.545932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7347b087d4d4'
down_revision: Union[str, None] = 'd35c5432f8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('extra_permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra_permissions')
    # ### end Alembic commands ###
