"""add_event_rnd_reports_table

Revision ID: d35c5432f8c1
Revises: df0fa7064f2c
Create Date: 2026-07-16 16:15:43.751667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35c5432f8c1'
down_revision: Union[str, None] = 'df0fa7064f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_rnd_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('actual_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('outcomes', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('faculty_count', sa.Integer(), nullable=False),
    sa.Column('external_count', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.String(length=200), nullable=True),
    sa.Column('learning_benefit', sa.String(length=300), nullable=True),
    sa.Column('guest_speakers', sa.JSON(), nullable=True),
    sa.Column('faculty_coordinators', sa.JSON(), nullable=True),
    sa.Column('student_coordinators', sa.JSON(), nullable=True),
    sa.Column('social_pamphlet', sa.JSON(), nullable=True),
    sa.Column('social_video', sa.JSON(), nullable=True),
    sa.Column('speaker_background', sa.Text(), nullable=True),
    sa.Column('session_report', sa.Text(), nullable=True),
    sa.Column('key_outcomes', sa.JSON(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('mode_of_delivery', sa.String(length=20), nullable=True),
    sa.Column('attendance_doc_path', sa.Text(), nullable=True),
    sa.Column('flier_path', sa.Text(), nullable=True),
    sa.Column('generated_report_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_rnd_reports')
    # ### end Alembic commands ###
